apiVersion: v1
kind: ConfigMap
metadata:
  name: root-ca
  namespace: kube-system
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDEDCCAfigAwIBAgIIY1ac0/RsiTAwDQYJKoZIhvcNAQELBQAwJjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MRAwDgYDVQQDEwdyb290LWNhMB4XDTI1MDQxNTEzMDQwMFoX
    DTM1MDQxMzEzMDQwMFowJjESMBAGA1UECxMJb3BlbnNoaWZ0MRAwDgYDVQQDEwdy
    b290LWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmxnKfybpaZ04
    ytlXkEU8NDHjtMoZo8grSdTKZCHp/CGOPCH+ihE1xZV3mGUnGB+o/AlWkQKNQjIO
    cBQOOwn9zzTequOVKLo958SFcX1BrXZvGKEPusUxGhw9mfMQ8rIMyNKtoz2L/0oG
    pU9vKnc42EVKLN8pA23IrN2jxhUw1JxokW1sc0t9QDKgIR6ljnr5aMQpDLKIReq9
    idsPqL2ar8Ys/q77C6SVaooH8wU6jZ1/TkfuCGC2Bw7P75GMxuRtnlmmJCIZRQUU
    xqMjfsD+oBCr5/PEC5HURA+xlzSm82AVRvwTNC+SZYG0V3DFRxjUOpsMO2i6UdBz
    f09tAljLRwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQUUNxlbjobVYwZ3InX3TxJXkt2qJgwDQYJKoZIhvcNAQELBQAD
    ggEBAFLNXRg1Jpgzi0I5sOBHL1ijaf3yZy5+R+riJYEOevKmYjpRMqI9rEV89Tb+
    sxIlIKjuXXJUDfG3MeOAyJG2F4y0IPm7R2obDkW8u+Pu71GaqjohSHl+O/yZcf76
    BPQVqFr0S5R464aBpakeI9Ut8Hu6d/GBF/YUwY3+B74gn/QiiHzI5T7+ENyyeoWj
    CrrBczoa4DnJgZnoLh1FlHqyu3JGRR6EfOJzSvIK6D4KsSxEg+eo7Ra1H9dKkDuB
    3UH60zGR7skLj6keHknynPkPUa+vRA7BEm70KR8GMhczt2PR/DOBuwGFb33PIwus
    TLc85dbQejEV2kvFX1W06jqdT9c=
    -----END CERTIFICATE-----
    
