apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  namespace: openshift-config
  name: pull-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJmYWtlIjp7ImF1dGgiOiJhV1E2Y0dGemN3bz0ifX19
