apiVersion: v1
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEoTCCA4mgAwIBAgIUQrT+gTZkrKCgjYnG+ym/bxe+/vswDQYJKoZIhvcNAQEL
    BQAwgZExCzAJBgNVBAYTAlBUMSAwHgYDVQQIDBdTb2JyYWwgZGUgTW9udGUgQWdy
    YcOnbzEgMB4GA1UEBwwXU29icmFsIGRlIE1vbnRlIEFncmHDp28xEzARBgNVBAoM
    Ck9uZU1hcmMuaW8xKTAnBgNVBAMMIE9uZU1hcmMuaW8gQXV0aG9yaXR5IENlcnRp
    ZmljYXRlMB4XDTI0MDkyMjIxNDU0NVoXDTI5MDkyMTIxNDU0NVowgZExCzAJBgNV
    BAYTAlBUMSAwHgYDVQQIDBdTb2JyYWwgZGUgTW9udGUgQWdyYcOnbzEgMB4GA1UE
    BwwXU29icmFsIGRlIE1vbnRlIEFncmHDp28xEzARBgNVBAoMCk9uZU1hcmMuaW8x
    KTAnBgNVBAMMIE9uZU1hcmMuaW8gQXV0aG9yaXR5IENlcnRpZmljYXRlMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4VTGfRioB8++d0GMNv8Vie9lP4Z+
    b787dlRvdUGCEmYrX++zuq07fbStInFEUhCABZBI17I2Pb+nnZ9lF/haVXK0S9TA
    H3FnByMIjSY9gqJGddRnCIqF+rqDxikJMDCKuoEIu10ZomvnMCkrpU/orPp0/iBx
    pZqQFTKbHQDP0DKxgBi+EpUXWPGUD2QX2wFeWXXZOxpt9THJRk0SbjqVAHYkHYks
    lS3O25UUlMBEot2o27v5ktWmMY05CHH+hYX1sOTz1z4FU3apZL1cwaVE5kL6Rh6p
    Jog+ReFhXQrrDZsCYlZCSDwnvifAiA9OHsXotMIA+jiJMX/SPb0EDsox9QIDAQAB
    o4HuMIHrMAwGA1UdEwQFMAMBAf8wHQYDVR0OBBYEFF43KoKQBB1G33+5p+4jMGx+
    rydwMIG7BgNVHSMEgbMwgbChgZekgZQwgZExCzAJBgNVBAYTAlBUMSAwHgYDVQQI
    DBdTb2JyYWwgZGUgTW9udGUgQWdyYcOnbzEgMB4GA1UEBwwXU29icmFsIGRlIE1v
    bnRlIEFncmHDp28xEzARBgNVBAoMCk9uZU1hcmMuaW8xKTAnBgNVBAMMIE9uZU1h
    cmMuaW8gQXV0aG9yaXR5IENlcnRpZmljYXRlghRCtP6BNmSsoKCNicb7Kb9vF77+
    +zANBgkqhkiG9w0BAQsFAAOCAQEAIeiA12gBNBckBIUvkb3aKQS7fXH9FLIE/5F0
    C7A7VnpnB0yBRmBQjAgNq9KlOsArySr+xnO3fWeDgHAzktXNz+9GXaj1c7PfWx3l
    oYiFCD857Kd3Br+Po3tgeJvnVjsaSSZMpkIiVhZnX0ywgI7YdchBaE4pCC2w0inP
    ZBAUJm0qo0wyurzBaaUaz73gElnjw/KPfepOMU5iNEMeKa2qPts+IyDlNC7B/Mi4
    k+w7YmeV8A7x5eFcqEJquZu/M53wBNeUPZmhxQGfKWSN8Ghi5V49c/84dlHY52KH
    z2DbK/qKbM/CYy5rvYSAQBcNCdQOE3zTstiqM394JOqlUc4c3g==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    openshift.io/owning-component: End User
  creationTimestamp: null
  name: user-ca-bundle
  namespace: openshift-config
