---
# tasks file for sys-package-manager-upgrade
- name: Update apt cache and upgrade packages (Debian/Ubuntu)
  hosts: all
  become: true
  tasks:
    - name: Update apt cache and upgrade packages (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        autoclean: yes
        autoremove: yes
        upgrade: "yes"
      when: ansible_facts['pkg_mgr'] == 'apt'

- name: Update dnf cache and upgrade packages (RHEL/CentOS/Fedora)
  hosts: all
  become: true
  tasks:
    - name: Update dnf cache and upgrade packages (RHEL/CentOS/Fedora)
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_facts['pkg_mgr'] == 'dnf'
